language: java
jdk:
- oraclejdk8
sudo: required
script: gradle clean check runTestNGTestCases -Psuites=TestNgSuiteCampaign.xml -PprimaryUserName=Aldo.Balderrama@mydomain.org -PprimaryUserPassword="$PRIMARY_USER_PASSWORD" -PremoteUserName=mabalderramav -PremoteKey="$REMOTE_KEY"
branches: 
only: develop
notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org
env:
  global:
  - secure: dOfh28bHxrjSh58g6cTv4XVbWWEFKrHa7X4NoZmshxbIMCmAtSJ3mUOJT+ReWg8WROh9LLXo6u3qu2mq1997aKbqlbeo/WAO2u/aIF7zMAEpwVo81CSFPXBUu6QoUmH/1jHiFbnv+bm3J1s9iuuL24uqzna2J+lWyyocm/cH364pDuDJjwSWwnm+qPoZvlHVFsVI+xqnUqf2gMJQxDmQ3936vDezyyMP+hF6Rskpb2TNCGCO7khUAO+LYdt4Dmhjpc6GjIo7QLhFIs9GUIpvnXLptNOGgKKym0OJJV/2NyHzTzUDGV6ouM/qyfOqyzlhkoKo4mfCClgU05dsjUmrAJa/dkHzHM7HQ76bu9BNNb6162AYABAnbrP+STDeexysIimpuRfMB4TQxxsLs+c8a+8uxAL8UmJvQLTVCmW5OrTkkH8AKRtktq5tABCtu5siWddNNXVdU69txk6928JeY5cXZr9PF3S76sGYFiWaJbLVhgj9/p+NkzbInSx7DBKZXqlGGaru2Zo1NdidgJGHOfNu+Jh7Lszpb4dYttRx8PB48PRWgTQ/jN195Vxfd4Iov5FvRhmX0aoWVVJ6GCVbOo+8Ty/5p8hAbsD0qgUQM6MxOcMSm+uJ9RVrwhYnzB0iE/UA8hXXKZeyTKguHR2/OXpILS3W0HoRNeEWFRbLxek=
  - secure: xSQI4eOOmOsHTnoyd4bIGwhEYdUW/iOI7/PdqUlAJ9s85XzfrWSrpJKjMll1kzvEHHy9TUkUSfJGEeOMz3x+pT4eMeduMvX+7IrbfU1quyOVOS1fp61UtGdjQgyqpTaAPyI618AdI1lYWFf1qJPEW5A5FkMzrHJ/NnRhVLmdzBtmb/6xO7guOZ4+LqnlWVp/7Ju8HTv0IcY8mkBJkurPvc9qJ7zNUmtuF2Xd9SsbKKBPKyScb085vd4mRyCsgkTO9RWbxoqra6f0duIFvjYhlRcE37vuSTxF2Aavh5cs8NkxKRyV7Rcb8sXvJ0c1kIDR3FIBPh2atZi3YKCe7vnl07nlTEC5VqCwhclRRY+ONgSAaHM53QBcmQpGW81T+Gjkdnsn3pTKffL345wYInKeRvnKBAoAseTQH86pC9jHzGkAimoMwOiwxNrG3JkUl8bF6XPioU5/nWMJcJxoTXcngXJ8eghHQKPmckBY4BrkiRFao5pbL1XtcJjZrFQN7KIZB7cC9R/5dHLV4JqCXIYndDv1P/2w176xcPUu4asX1WCxcf6AzBXnqzXq2lB9oJJrCVTx941eEKAA15nJOpX8tWWVdunjC7H7Js41b9i6hJRpmJ2uke4e6vXQSUqBZiZZUIQ7nacpnXCzvfaHQi3JmPdHsIPx0XMmFwPRGwcqjXo=
