language: java
jdk:
- oraclejdk8
sudo: required
env:
  global:
  - secure: kQks4Cd//AgTymNRrUM2LWTUr8RZkSlG38U98zINeoPgMn6sTAsmX1E+6cJLbrMifJPWyoqgxE79ikEhPBNOLfUBnBLB+Jymba31FqjzMAVP6kPD1rJpOiK5uWDFZoebShs1y+BF7kNMviPCH8dKUFVQ+r19AWdsYQFB6g8mHY33YdognvX5v8jr68yUYp+EJeYfMrKY1i33rODf+LYn8Z/gWhzGU8EM2x+Yvkemv5r0N7M5pTwzemiZycjIcp5glhV3QQtTJTYCOwtnmJS3o0zUNtD95aGES2mWKlIRqeVAPvTVgWIyRqAnGKuM8yU/FJs+/VNKE02a11HP3URR/6o4aM8u6YVKvwtEsCfRk4dyC3Fz5SLMcbHJbqfJKifjKk9F8obp+X8JpgFfOLrdFQXyqfg28rIko+DhX/0AuyaWQcTvtYXayDv8nycnUpVMBmVapp4FUBCfMAYstV6cglrYtfOD4PtpCfpa7PtRLbAiSiSGKdSeaSR/7zXJGOhUK+5lUQ9QeUJZczuzWYarPjeM0j0pN/5Iy0I6WzqLKxd3YQxBQxxxtB/p74o3NbiBZMKLfwsTQTUqFi7z21646wi6sNfe2JoFOI+PIgXMYx6sEREwM5WX4l9pbk29jtny05CYbBjGGHjmJS3kjaJE9C73ZnjME7tyV3hEsT/8kI8=
  - secure: RFNdnb+tqEiGwKONzWvY8iaEP1elRWvdz0E8iOQs4a8somiIqYRWBCY4/66kY9C9/VWXNP79Ab+S/NGFN7e1Uxk3JCVd5lsNIMEwEIl8qKzcUNZt+npfGoigcBO0909gJ1mEJEYUcgwGiOLD6mYizAgkde5MCXNX1eq75SPb69eyKVuCb8k8RbS6MCQPG509F4znUc9uVwv6Bc5LLJqNuUXfVSa+qgW8R+cGhVDVBExiaWZ4KCiWC/ykqQPeG4ZkTn4v6w+ZsWgvUOOsBafcl4ua7YcKkhCglL+FTScQy3zZ9K4A1XUJtX2ytr4M8SbdaiiAnyqKLTP8Q+z8OkEfAkLlts95aF1c+EuqXQDz0UGGr2mlGNyhPXLdXie2UPu/ZtP/3o0j+A8JIchVLyBsrBgcO14cmoMwYb08q1AVRmgl8yvqYCDB+F2LZH67jBWFrBQRyMjL9uiYJ1iog/zBwBmqQLdJrS6KG21xGcgRe3Ts1pBYJYh2A8k99kXr5mXGzcNr2dQnzAiAAepnSvOZ2Fj0RVlyfBR8bKkRYbJLlodTHNGqP5dFa1nZaEwCLC0+0AOnumDPRfi+p0bMzSgxbXVc623fa6k8vuziDNP02+hDgJNNzedk7hFJvh7faPnngYPRLmu7seRGCpQFsYVdT5ToexD1Qnas/J3OtXukbzE=

script: gradle clean check runTestNGTestCases -Psuites=TestNgSuiteCampaign.xml -PprimaryUserName=Aldo.Balderrama@mydomain.org -PprimaryUserPassword=P@ssw0rd -PremoteUserName=mabalderramav -PremoteKey="$REMOTE_KEY"
branches: 
only: develop
notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org
