language: java
jdk:
- oraclejdk8
sudo: required
env:
  global:
  - secure: Cbs+9Mk1iIwGh8rBs1lmJaZhRiknhSv2GqOV9HhMu3aUjHG9PrNUrMpk54BWGkq/Tg51Y3aPSCK5dmge66Oo+2gwpgBh0zdWb3IHugJG+aQVPFjAAkp86SmNQLu2nXxy4J4MVVj+etBBjp9jSI3JmG765kBHgqEue4w4zo/JBASgHdvT0zgpFthwx59ZLWmMDSfvRPQS/XjnovC/eVzNw7D+ZQ62dJB2C4KNUYzjEWWofBK2FzQZ4TJbAemIdSKTImlekEswK2yMFWRwgXl9Mb4oI9WZHXkHfmRkTFdxIacr3qnGd5rN2wrucwSRvrIibAN/BTVeCqNht7gaql9iBuUMeB1hdEl2zV8IaumnMgXh/xS8H22ovICDDMcv2HfLBKt0oQJoM5TQsVCJpo3C8mx0hwI5Dh42D6QHrTLVt+eNzRDBLklF3yVtyoss/2TmiWii88YqznQuT++LFZpKZIZRmJP8CCA7QsYxoA1a8CPGckrggcDGgLdf+QrKiv1YLAO4MfbE00Ot2tnplst33aZDcyhtusLSKJkM6bedI4eOHF5//7MFyb3TFGsLxp8vZEK1T9gS5hlwWIL490q/xnvTkfxhvaPKn7IP56O8wJM8uMp0mYsK0awNTEmuh+yKSLyXUdB59vOohGSAgkqzJJn8vJ+lWdPWKx8SHfxXYdg=
  - secure: RNfHyVVhgGqcToabeljl/8gBE9AJQob7LQQGtc0aoNpXyyOXA2kgKKjbckZ6haQXczb6EYfAIaatGozq8Bkg6/hZzqcFHgEt9EF3RywYF0rPvCuKccshFk/RD2zWex+UOUs2EMrjn0xkqQt/qiIYgpEXNkIFiyXNZbGDhHzOTu/xzkQ3zENBwr+q4vyATN3ez7T7lIFLhF/JBZQ/+nS+q0XvOn4561++0iiKGEixKcizkoeh3tW/w+lzujDmdUO20fGc31zAwn+/o6qbCc5NaYMGgcLC8SIVj5lsG35OSNdbe6ePT3TcmOBrbJtQyXoHwiB/6/UweYH00UfRefehWvGFZhadKWrPFl1eirAczMUx7VHa5n98IwiB1rZZC4jg27mysNkwWykG+0hMbzoFjlVsbogTPaUSEVr8FH2z0gWhnj3qRIaJlJ2gwgqVNlYdXUpfo5Bh/FRvopKOyAPMugjP7ZmFM7bcahrgZO+PWahlKHHxOYOVZvS4kY8e326EsZUyA+FclJsPbOuyMCYOif+cYdfy0MYmwUYOGCalByYX2qehupKWaZIkkYnmXw3x4T7l6BotCPAvFrVF5G/wRyhw6v4A13LKOUVZyoCgLFRFkLHO85acMGAlypyq+yFxO65uEka01/hxz/cbifFhhDx6Xc/CLHmKlRpqudT+UnE=
script: gradle clean check runTestNGTestCases -Psuites=TestNgSuiteCampaign.xml -PprimaryUserName=Aldo.Balderrama@mydomain.org -PprimaryUserPassword="$PRIMARY_USER_PASSWORD" -PremoteUserName=mabalderramav -PremoteKey="$REMOTE_KEY"
branches: 
only: develop
notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org

