language: java
jdk:
- oraclejdk8
sudo: required
env:
  global:
  - secure: M5pb68c1qNKkOeFMGsPgmjqmPX/vDardXrINzHn/6RAKERIuILrC9vuiLPk5ahHguzbC4oIaECGC9cBEYzdZwpYE/GtklUvbLIlE7HpoIpAM4IllGLtd87yqPr3KwFG+Vz2CyteBPwWt8rFwzFT6EfWZgyXiymCk2JwbuFHrSGjWkpM9WCkzI6G4OvilC7d30NB0PSJtow+kt/GwEawPS6t/Cc4zQrtQnQdyFEkX4AxQ06/MtTk+icsrjWFl+RRhSidzfPwKTK6fxs96C/hiLhL84gp2+H2jzQCOXxY7mVibCxNvvsoTNoGePTFtcCHe2GbGViWAiprqY8c2JKqwO4MSlNy458zWwcKdMkjdpGQbhmBMDXdYOCQSne2DDJN4NFD0viuqPLlgKOdqwWAZeiIBHGHP9ZhxPdCBRsezqmV+s5i53JnPda/U3hPX0g7Vs+gSCLGr4LEWzsAcnPbNRaZ5JPAcafkO8elCt5PItC+VKVhNNiqGgIR7vMGeDbMcv9vU0JidRevU0hBg033/RlD0hSu8MS9aUT6kuqwwvvjvVcp4+8e1uTTJ0PcRnFp7AvUM3nVjTRUP8N4dwrMUUsOhd3F9oWlt6GOb8XMQGXDS/PsvmlM8Yh+LLcaMYLk+6aZs+KBZH5q8tbDAcOY48wzlm1uVda8ebqmGIdHHoeU=
  - secure: uaGzq5kl4l7tioZpRPREhIKdLMfQoabhyco/ad6qOdmcJag/VOS8lUvNHIDux2QrXQsO5JyK5a6GFjzlC9hVRjFwt00lC6YcT83bqS5xC4zpG5LjzAeXXUQXk0ZW2QnOiv2OtRvb8uZkAq1AT/oEZyt/rfhTm2pTbEisuWV1KT0aKJ/bEjgUs6lDnxwyW9Sl9JHmTBYn1wThX0TUSeCwiUVJcCr2VcKY0vKqdBDqrPrO2r4hGnTPM9aPg4SfplcK/Gv6RJ1uGgkLOADSKqckniy+WC1Jt0Szodj17soCtEg1mtMb5AsEg+3FhMYlJVTmTtSSe/QRrya00plb9rLe4l5ncYjS87wCHnh7SRox8c31Uj57EGG28wj0hzmC0qJ8RgJBeYk+84kKrIlxXCAyaC3IMZVZVEU0NjE5GSS3FNEKoq4T/AlI2ZR8yhzBDnsACWkZBHGhVGZ6ICB6U/bGFCfbLip7oEdQ4OZPlrUIaeBkcVxe1vTVzMUTi9OFoyW/bqxuGm9b4Ag15XKZBSTr4OGk+Jis8x/bSH+xR93afMMZSWKw62DhIiXuVY+dQ4CTI6VvOz7eQdaUEfjidVJE/Bx40ZlGsax2G+E55h916xAQuphFCyNoofBrhh4PlTWcSoPGwqyaNZqx4mPIQ4lu3kbYeWRxmInkiSRF2IhbFOw=
script: gradle clean check runTestNGTestCases -Psuites=TestNgSuiteCampaign.xml -PprimaryUserName=Aldo.Balderrama@mydomain.org
  -PprimaryUserPassword="$PRIMARY_USER_PASSWORD" -PremoteUserName=mabalderramav -PremoteKey="$REMOTE_KEY"
branches: 
only: develop
notifications:
  email: true
  recipients:
  - carlos.gonzales@jalasoft.com
  - AT01@fundacion-jala.org

